whamcloud/Online-Help

- .travis.yml
- package.json
- Install node along with using ruby. This should use the latest version of node and npm to publish.
> Fix deploy

- package.json
- Change name from @iml/help-docs to @iml/online-help
> Change name from @iml/help-docs to @iml/online-help

- _config.yml
- package.json
- change base url from /static/webhelp to /help
> Update base url

- package.json
> - Bump to version 2.1.0

- package.json
> - Updated version to 2.2.0

- docs/Contributor_Docs/cd_Managed_ZFS.md
- docs/Contributor_Docs/cd_TOC.md
- Add section for Managed ZFS file system creation in contributor docs
- Add Managed_ZFS section to TOC
> - Add section for Managed ZFS file system creation in contributor docs

- docs/Contributor_Docs/cd_Create_Offline_Repos.md
- docs/Contributor_Docs/cd_Setting_Up_Clients.md
- docs/Contributor_Docs/cd_TOC.md
- Add "Create_Offline_Repos" article to contributor docs
- Add "Create_Offline_Repos" to contributor docs TOC
> - Add "Create_Offline_Repos" article to contributor docs

- package.json
> - bump to version 2.3.0

- docs/Contributor_Docs/cd_Building_IML.md
- docs/Contributor_Docs/cd_TOC.md
> Add a doc on how to build IML

- docs/Contributor_Docs/cd_Monitored_Only_ZFS.md
The monitored only ZFS doc has a few
inaccuracies. In particular:
- NetworkManager does not need to be stopped / disabled.
- We should not need to reformat or force.
- The failover and mgs args should point to LNet addresses,
not the box hostnames.
- We should export datasets until the manager syncs up before
mounting.
> Update monitored only ZFS doc

- .gitignore
- .npmignore
> Ignore vendor dir.

- docs/Contributor_Docs/cd_UnInstall_IML.md
> - Uninstall updates

- docs/Contributor_Docs/cd_Installing_IML_On_Vagrant.md
- docs/Contributor_Docs/cd_Managed_ZFS.md
- docs/Contributor_Docs/cd_Setting_Up_Power_Control.md
- Online-Help #33
- Created a file for Setting up Power Control
- Added the link to the file in two places.
Signed-off-by: Peter Robinson <peter.timothy.robinson@gmail.com>
> Extract fence_vbox

- docs/Upgrade_Guide/Upgrade_EE-2.4-el6_to_LU-LTS-el7.md
- docs/Upgrade_Guide/Upgrade_EE-3.1-el7_to_LU-LTS-el7.md
Also a small consistency change
Signed-off-by: Brian J. Murrell <brian.murrell@intel.com>
> Add the lustre-ldiskfs-zfs to node 1 instructions

- package-lock.json
- package.json
> bump marked

- docs/Install_Guide/ig_ch_16_appD_getting_help.md
Fixes #61 
Signed-off-by: Tom Nabarro <tom.nabarro@outlook.com>
> Remove references to Jira in getting help page

- docs/Contributor_Docs/cd_Monitored_Only_ZFS.md
- Fix a bug in one of the commands
- Update how the interfaces are configured
> Monitored Only ZFS updates

- docs/Contributor_Docs/cd_TOC.md
Add item for Lustre clients to TOC
> Add item for Lustre clients to TOC

- iml-online-help.spec
Signed-off-by: Brian J. Murrell <brian.murrell@intel.com>
> Use https for the Source0 URL

- docs/Contributor_Docs/cd_Monitored_Only_ldiskfs.md
- docs/Contributor_Docs/cd_TOC.md
Fixes #55.
Signed-off-by: Will Johnson <william.c1.johnson@gmail.com>
> Create contributor doc for creating a monitored ldiskfs filesystem

- docs/Upgrade_Guide/Upgrade_EE-2.4-el6_to_LU-LTS-el7.md
- docs/Upgrade_Guide/Upgrade_EE-3.1-el7_to_LU-LTS-el7.md
Update upgrade doc such that corosync and pacemaker are enabled upon reboot
> Update upgrade doc such that corosync and pacemaker are enabled upon reboot

- _config.yml
- docs/api/api_TOC.md
> test to make version a variable

- _config.yml
- docs/Contributor_Docs/cd_Installing_IML_On_Vagrant.md
- docs/Contributor_Docs/cd_Managed_ZFS.md
- docs/Contributor_Docs/cd_Monitored_Only_ZFS.md
- docs/Contributor_Docs/cd_Monitored_Only_ldiskfs.md
- docs/Contributor_Docs/cd_TOC.md
- docs/Contributor_Docs/cd_Things_To_Learn.md
- docs/Introduction_1_0.md
- package.json
> Update Introduction Page

- docs/Getting_started_2_0.md
> - Update Getting Started page

- docs/Monitoring_lustre_fs_4_0_0.md
- Update Monitoring Lustre page
> - Update Monitoring Lustre page

- .travis.yml
- Makefile
- _config.yml
Update lustre and iml versions in config to reflect latest.
> Update lustre and iml versions in config to reflect latest.

- docs/Contributor_Docs/cd_module_tools.md
Update module-tools doc with more info on building SRPMs and how some
steps are optional.
> Update module-tools doc.

- docs/Contributor_Docs/cd_Setting_Up_Power_Control.md
Update power control docs.
Signed-off-by: Will Johnson <william.c1.johnson@gmail.com>
> Update power control docs.

- docs/Contributor_Docs/cd_Installing_IML_On_Vagrant.md
- docs/Contributor_Docs/cd_Managed_ZFS.md
- docs/Install_Guide/ig_ch_05_install.md
IML 4.1 changes the method of installation from
a local tarball to a rpm repo driven install.
This PR will address the new install method.
> Update install instructions

- .travis.yml
- Makefile
Fixes #106.
Like our other repos, Online-Help should be updated to provide continuous deployment via a travis stage.
> Setup continuous deployment

- Makefile
- include/travis/copr-deploy.sh
> Move install_build_deps

- Makefile
- iml-online-help.spec.in
> Add "install_build_deps" to Makefile

- docs/Contributor_Docs/cd_Setting_Up_Power_Control.md
> Ensure ~/.bashrc is updated when configuring power control

- docs/Upgrade_Guide/Upgrade_EE-2.4-el6_to_LU-LTS-el7.md
Make a section in the upgrade doc a bit clearer
> Make a section in the upgrade doc a bit clearer

- docs/Contributor_Docs/cd_Remote_Python_Debugging.md
> Add guide to debugging running Python process with GDB

- docs/Contributor_Docs/cd_Building_IML_4.0.x.md
- docs/Contributor_Docs/cd_TOC.md
Add instructions describing how to build IML@4.0.x locally
> Add instructions describing how to build IML@4.0.x locally

- docs/Contributor_Docs/cd_Building_IML_4.0.x.md
> Update location of installer in Building_IML_4.0.x.

- docs/Contributor_Docs/cd_Building_Rust_RPMs.md
- docs/Contributor_Docs/cd_TOC.md
> Add doc for building rust RPMs

- Makefile
- _config.yml
- iml-online-help.spec.in
- package-lock.json
- package.json
> Bump for IML 4.0.9

- docs/Contributor_Docs/cd_Building_Rust_RPMs.md
A few things were missing / inaccurate.
> Update Building Rust RPMs

- docs/Install_Guide/ig_TOC.md
- docs/Install_Guide/ig_docker_stack.md
IML 5+ can be deployed using docker stack.
Document the general process.
> Document docker stack deployment

- docs/Install_Guide/Pkg_Guide.md
- docs/Upgrade_Guide/Upgrade_EE-2.4-el6_to_LU-LTS-el7.md
- docs/Upgrade_Guide/Upgrade_EE-3.1-el7_to_LU-LTS-el7.md
> Update packaging guidelines for repolist in place of bundles

- Makefile
- _config.yml
- iml-online-help.spec.in
- package-lock.json
- package.json
> Update docs for IML 4.0.10.0

- docs/Upgrade_Guide/Installing_Updates.md
I found a broken link under docs/Upgrade_Guide/Installing_Updates.md.
This patch fixes the broken link.
> Fix broken link

- _config.yml
> Bump version to 5.0

- docs/Create_and_manage_ZFS_based_LFS_8_0.md
Fixes Issue #87 
Signed-off-by: Nathaniel Clark <nclark@whamcloud.com>
> Update zfs managed docs

- docs/Upgrade_Guide/ug_TOC.md
- docs/Upgrade_Guide/upgrade_iml-4.0-el7_to_iml-5.0-el7.md
- Update a couple of sections in the upgrade docs.
> Small upgrade to upgrade documentation

- docs/Contributor_Docs/cd_Running_IML_On_Docker_With_Vagrant_Servers.md
- docs/Contributor_Docs/cd_TOC.md
- docs/Install_Guide/ig_docker_stack.md
> Docker docs update

- docs/Contributor_Docs/cd_Installing_IML_On_Vagrant.md
> Fixup vagrant install docs

- docs/Upgrade_Guide/upgrade_iml-4.0-el7_to_iml-5.0-el7.md
> IML 5.0.0.0 repo link is broken in upgrade docs.

- docs/Upgrade_Guide/Installing_Updates.md
- docs/Upgrade_Guide/Upgrade_EE-3.1-el7_to_LU-LTS-el7.md
Related to whamcloud/integrated-manager-for-lustre#1017
Signed-off-by: Nathaniel Clark <nclark@whamcloud.com>
> Add documents for 4.0.10.2

- _config.yml
> Update lustre version to 2.12.2

- docs/Contributor_Docs/cd_Jenkins_Pragmas.md
- docs/Contributor_Docs/cd_integrated-manager-for-lustre_Unit_Testing.md
> Document COPR Module Manager pragma

- .travis.yml
- _config.yml
- docs/Install_Guide/ig_ch_05_install.md
- docs/Upgrade_Guide/Installing_Updates.md
- docs/Upgrade_Guide/upgrade_iml-4.0-el7_to_iml-5.0-el7.md
- iml-online-help.spec
- package-lock.json
- package.json
> Updates for 5.1.

- docs/Contributor_Docs/cd_Running_IML_On_Docker_With_Vagrant_Servers.md
- docs/Install_Guide/ig_docker_stack.md
> Update help docs to describe new docker setup.

- docs/Install_Guide/Create_Offline_Repos_10_0.md
> Update cert paths

- .copr/Makefile
- .travis.yml
- _config.yml
- docs/Contributor_Docs/cd_Running_SSI_Tests.md
- docs/Release_History.md
- iml-online-help.spec
- package-lock.json
- package.json
> bump version

- docs/Contributor_Docs/cd_integrated-manager-for-lustre_Unit_Testing.md
The python unit test instructions do not currently work. Update the
instructions to include missing steps.
Signed-off-by: johnsonw <wjohnson@whamcloud.com>
> Update python unit test instructions
