_config.yml
package.json

- reset config properties in _config.yml as it is affecting  
https://intel-hpdd.github.io/Online-Help/
- Define baseurl and destination as arguments to the build script

Fix https://intel-hpdd.github.io/Online-Help/

---

package.json

There is an unnecessary tar file in the published package. It needs to be removed.

- Remove unnecessary tar file

---

docs/Config_and_using_HSM_6_0.md
docs/Contributor_Docs/cd_Setting_Up_Clients.md
docs/Contributor_Docs/cd_UnInstall_IML.md
docs/Errors_Troubleshooting_12_0.md
docs/Install_Guide/ig_ch_03_building.md
docs/Install_Guide/ig_ch_04_pre_install.md
docs/Install_Guide/ig_ch_07_configure_clients.md
docs/Install_Guide/ig_ch_11_updating.md
docs/Install_Guide/ig_ch_15_appC_backup_recovery.md
docs/Install_Guide/ig_ch_16_appD_getting_help.md
docs/Introduction_1_0.md

- Replace all references of chroma-diagnostics with iml-diagnostics.
Some of the wording and code snippets needed updating as well
- Add required missing instructions for HSM
- Fix a small bug in cd_Setting_Up_Clients.md

- Remove all references to centOS 7.3 as we only support 7.4

---

docs/Contributor_Docs/cd_Monitored_Only_ZFS.md

Now that disks have consistent serials, we can update the docs to use them.
That means the commands to create zpools in ZFS MO mode are now the same between VM instances.

Make ZFSMO instructions repeatable

---

docs/Contributor_Docs/cd_Managed_ZFS.md

- Now that the serial numbers have been hard coded we can update the
code blocks in the managed zfs contrib docs. This will make it easier
as we will no longer have to have two windows open side by side to
read off he serial numbers. Instead, we can just copy / paste.
Signed-off-by: Will Johnson <william.c1.johnson@gmail.com>

Update ZFS Managed code blocks using hard coded serials

---

README.md
docs/Upgrade_Guide/Upgrade_EE-2.4-el6_to_LU-LTS-el7.md
docs/Upgrade_Guide/Upgrade_EE-3.1-el7_to_LU-LTS-el7.md
docs/Upgrade_Guide/ug_TOC.md

Verified upgrade process from EE 2.4.2.7 on EL 6.8 to Lustre 2.10.1 LTS + IML 4.0RC2 on EL 7.4

EE 2.x to community Lustre LTS and IML 4.0 upgrade documentation

---

docs/Contributor_Docs/cd_Monitored_Only_ZFS.md

Fixes #56.
The monitored zfs docs currently specify that the zfs software should be
installed before adding the servers to IML. The problem is that if you
attempt to install zfs on the servers before the agent is deployed it
will not be able to find the packages it needs to install zfs. The docs
should be updated to reflect this.
Signed-off-by: Will Johnson <william.c1.johnson@gmail.com>

Update monitored zfs docs

---

include/.gitrepo
include/travis/copr-deploy.sh
include/travis/run_in_centos7_docker.sh

subrepo:
subdir:   "include"
merged:   "79a95c2"
upstream:
origin:   "git@github.com:intel-hpdd/module-tools.git"
branch:   "master"
commit:   "53a1bd6"
git-subrepo:
version:  "0.4.0"
origin:   "https://github.com/ingydotnet/git-subrepo"
commit:   "74339e8"
Changes:
* 53a1bd6 - Fix a couple of errors (#27)
* dd7121f - Display contents of RPMs built in mock_build_test.sh (#28)
Signed-off-by: Brian J. Murrell <brian.murrell@intel.com>

git subrepo commit (merge) include

---

Makefile
iml-online-help.spec
package.json

Online-Help 2.4.0 pointed at a dir which didn't correspond with nginx.
Update the path, we will update Nginx in a subsequent IML release.

Update online-help path

---

docs/Contributor_Docs/cd_Debugging_Node_In_Vagrant.md
docs/Contributor_Docs/cd_TOC.md

Add a section on debugging a running nodejs
process in Vagrant.
This is useful for stepping through problems
on a live node.

Add section on debugging nodejs in vagrant

---

docs/Upgrade_Guide/Upgrade_EE-2.4-el6_to_LU-LTS-el7.md
docs/Upgrade_Guide/Upgrade_EE-3.1-el7_to_LU-LTS-el7.md

Remove references to a patchless kernel.
Fixes #89.

Remove references to a patchless kernel.

---

docs/Contributor_Docs/cd_TOC.md
docs/Contributor_Docs/cd_module_tools.md

In order to test specific builds from n repos at once, we need to host
them in copr repos and tell Jenkins about them in a commit pragma.
This PR adds a doc on how to do this.

Add doc on using module-tools

---

docs/Contributor_Docs/cd_Installing_IML_On_Vagrant.md
docs/Contributor_Docs/cd_Managed_ZFS.md

Fixes #103.
We do not need the power control section in this document as it will be included in the docs specific to which kind of filesystem they are creating (ldiskfs, zfs). Remove the "Setting up Power Control" section from Installing IML on Vagrant.

Remove "Setting up Power Control" from Installing IML on Vagrant

---

docs/Contributor_Docs/cd_Installing_IML_On_Vagrant.md
docs/Contributor_Docs/cd_Monitored_Only_ZFS.md
docs/Contributor_Docs/cd_Monitored_Only_ldiskfs.md

Update monitored-only ZFS and ldiskfs
Fixes #101.
Fixes #102.
- Update moniotred only ZFS and ldiskfs
- Update interface configuration on "Installing IML On Vagrant"

Zfs and ldiskfs

---

docs/Contributor_Docs/cd_Installing_IML_On_Vagrant.md

for monitor only filesystems and the gui procedure is followed for
managed filesystems.

Update "Configure Interfaces" such that the the provision script is run

---

docs/Contributor_Docs/cd_Managed_ZFS.md

SCD - Creating a Managed Lustre ZFS Filesystem on a Vagrant virtual cluster
Fixes #105.
Remove the documentation on zpool creation and instead instruct the user to run the provisioning script

SCD - Creating a Managed Lustre ZFS Filesystem on a Vagrant virtual cluster

---

docs/Contributor_Docs/cd_Installing_IML_On_Vagrant.md

Fixes #111.
The Installing IML On Vagrant document should link to the following setup documents:
Managed ZFS
Monitored Only ZFS
Monitored Only Ldiskfs

Link to setups at the bottom of "Installing IML On Vagrant"

---

docs/Contributor_Docs/cd_Setting_Up_Power_Control.md

Fixes #123.
We no longer need to run power control twice. Update the docs to reflect this.

Power Control - No longer need to run twice

---

docs/Upgrade_Guide/Upgrade_EE-2.4-el6_to_LU-LTS-el7.md
docs/Upgrade_Guide/Upgrade_EE-3.1-el7_to_LU-LTS-el7.md

The location constraints in the upgrade docs are being set using "pcs
constraint location ...". This will set the constraint but the format of
the constraint will not match what IML is expecting. As a result,
operations on the resource issued by IML will fail becasue it will not
be able to match the resource name. The IML source shows that the
constraints are being added using cibadmin. The instructions should use
the same command such that the resource names match.

Fix location constraint operation in 2.4 upgrade docs

---

docs/Upgrade_Guide/Upgrade_EE-2.4-el6_to_LU-LTS-el7.md

We have encountered two cases in which the location was not "primary" or
"secondary" when the location constraints are defined. Add a note to
emphasize that -primary or -secondary must be specified.

Emphasize location constraint in upgrade docs from 2.4 to 4.x

---

docs/Contributor_Docs/cd_Remote_Python_Debugging.md

Instead of using telnet, we can get readline support if we use socat.

Update doc on using RemotePdb

---

docs/Contributor_Docs/cd_Debugging_Node_In_Vagrant.md

Add the process to debug a running nodejs process
via cli.

Add cli debugging to node debugger docs

---

docs/IML_Help_TOC.md
docs/Install_Guide/Create_Offline_Repos_10_0.md
docs/Install_Guide/ig_TOC.md

The offline repo doc is currently under the online help section, but it
makes more sense for it to be under the install guide section.

Move Offline repo doc

---

docs/Upgrade_Guide/Upgrade_EE-2.4-el6_to_LU-LTS-el7.md
docs/Upgrade_Guide/Upgrade_EE-3.1-el7_to_LU-LTS-el7.md
docs/Upgrade_Guide/upgrade_iml-4.0-el7_to_iml-5.0-el7.md

Add some additional text to underscore that they may need to backup
additional data, such as multipath configurations, which may not be on
all systems.

Update Backup Script

---

docs/Contributor_Docs/cd_integrated-manager-for-lustre_Unit_Testing.md

The unit testing docs are outdated. Update these docs to reflect how
testing works in travis and use a docker container to run tests locally.

Update iml unit testing docs

---

docs/Upgrade_Guide/Upgrade_EE-3.1-el7_to_LU-LTS-el7.md

Recently, there has been a few issues following an upgrade from
3.1.1 to 4.0.10.1:
1. Transaction error during nodejs upgrade
1. Transaction error during Django-south upgrade
1. rabbitmq-server is not upgraded
Include instructions in the upgrade guide to resolve these issues before
running the installer.

Update upgrade docs

---

docs/Upgrade_Guide/Installing_Updates.md

The upgrade path currently shows that customers can upgrade from 3.1.x
to 5.0.0.0. This is incorrect as they will need to upgrade to 4.0.10.1
first, then upgrade to 5.0.0.0.

Update upgrade path instructions

---

docs/Contributor_Docs/cd_Running_IML_On_Docker_With_Vagrant_Servers.md

- Setting up power control with docker is slightly different. Add
instructions on how to do this in the docker section.

Add power control section to Docker instructions

---

docs/Install_Guide/ig_docker_stack.md

Add another step so user's can utilize the `iml` command outside the
docker swarm.

Add wrapper script for IML CLI in docker

---

docs/Contributor_Docs/cd_UnInstall_IML.md

Starting in IML 5.0.0 files have been added to the /etc/iml/ directory.
If this folder is not removed after uninstalling and then the server is
used again it will contain cached data that will prevent volumes from
being picked up by iml. This patch updates the "Remove Agent Software"
section to ensure that this directory is removed.
Signed-off-by: johnsonw <wjohnson@whamcloud.com>

Update uninstall instructions for the agent side

---

docs/Contributor_Docs/cd_Running_IML_On_Docker_With_Vagrant_Servers.md

Option -h in iml server add leads to help output
According to options description:
FLAGS:
-h, --help       Prints help information

 fix: Remove -h help option from  server add
